language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
    - "echo 'TRAVIS: true' >> serverless.env.yml"
after_success:
    - npm run deploy -- --conceal
branches:
  only:
  - master
