language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
    - "echo 'TRAVIS: true' >> serverless.env.yml"
deploy:
  - provider: script
    script: npm run deploy -- --conceal
    on:
      branch: master
