language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
    - "echo 'TRAVIS: true' >> serverless.env.yml"
deploy:
  skip_cleanup: true
  provider: script
  script: yarn deploy --conceal
  on:
    branch: master
