service: sls-data-extraction

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs6.10
  cfLogs: true
  versionFunctions: false
  environment:
    DB_HOST: ${file(serverless.env.yml):DB_HOST, env:DB_HOST}
    DB_DATABASE: ${file(serverless.env.yml):DB_DATABASE, env:DB_DATABASE}
    DB_USERNAME: ${file(serverless.env.yml):DB_USERNAME, env:DB_USERNAME}
    DB_PASSWORD: ${file(serverless.env.yml):DB_PASSWORD, env:DB_PASSWORD}
    GITHUB_TOKEN: ${file(serverless.env.yml):GITHUB_TOKEN, env:GITHUB_TOKEN}

functions:
  # Daily statistics for all properties: sell
  base-data-sell:
    handler: src/base-data.run
    environment:
      PROPERTY_CATEGORY: sell
    events:
      - schedule: cron(15 0 * * ? *)

  # Daily statistics for all properties: buy
  base-data-buy:
    handler: src/base-data.run
    environment:
      PROPERTY_CATEGORY: buy
    events:
      - schedule: cron(10 0 * * ? *)

  # Daily statistics for all properties: rent
  base-data-rent:
    handler: src/base-data.run
    environment:
      PROPERTY_CATEGORY: rent
    events:
      - schedule: cron(5 0 * * ? *)

  # Daily statistics for all properties: want-to-rent
  base-data-want-to-rent:
    handler: src/base-data.run
    environment:
      PROPERTY_CATEGORY: want_to_rent
    events:
      - schedule: cron(0 0 * * ? *)

  # Weekly market share analysis
  market-share:
    handler: src/market-share.run
    events:
      - schedule: rate(7 days)

  # Median monthly SELLING price for APARTMENTS in Riga
  regional-data-apartment-sell-monthly:
    handler: src/regional-data.run
    environment:
      REGION: riga
      PROPERTY_CATEGORY: apartment
      PROPERTY_TYPE: sell
    events:
      - schedule: cron(30 0 1 * ? *)
  regional-price-per-sqm-apartment-sell-monthly:
    name: RegionalPricePerSqmApartmentSellMonthly
    handler: src/regional-price-per-sqm.run
    environment:
      REGION: riga
      PROPERTY_CATEGORY: apartment
      PROPERTY_TYPE: sell
    events:
      - schedule: cron(31 0 1 * ? *)

  # Median monthly RENT price for APARTMENTS in Riga
  regional-data-apartment-rent-monthly:
    handler: src/regional-data.run
    environment:
      REGION: riga
      PROPERTY_CATEGORY: apartment
      PROPERTY_TYPE: rent
    events:
      - schedule: cron(35 0 1 * ? *)
  regional-price-per-sqm-apartment-rent-monthly:
    name: RegionalPricePerSqmApartmentRentMonthly
    handler: src/regional-price-per-sqm.run
    environment:
      REGION: riga
      PROPERTY_CATEGORY: apartment
      PROPERTY_TYPE: rent
    events:
      - schedule: cron(36 0 1 * ? *)

  # Median monthly SELLING price for HOUSES in Riga
  regional-data-house-sell-monthly:
    handler: src/regional-data.run
    environment:
      REGION: riga
      PROPERTY_CATEGORY: house
      PROPERTY_TYPE: sell
    events:
      - schedule: cron(40 0 1 * ? *)
  regional-price-per-sqm-house-sell-monthly:
    name: RegionalPricePerSqmHouseSellMonthly
    handler: src/regional-price-per-sqm.run
    environment:
      REGION: riga
      PROPERTY_CATEGORY: house
      PROPERTY_TYPE: sell
    events:
      - schedule: cron(41 0 1 * ? *)

  # Median monthly RENT price for HOUSES in Riga
  regional-data-house-rent-monthly:
    handler: src/regional-data.run
    environment:
      REGION: riga
      PROPERTY_CATEGORY: house
      PROPERTY_TYPE: rent
    events:
      - schedule: cron(45 0 1 * ? *)
  regional-price-per-sqm-house-rent-monthly:
    name: RegionalPricePerSqmHouseRentMonthly
    handler: src/regional-price-per-sqm.run
    environment:
      REGION: riga
      PROPERTY_CATEGORY: house
      PROPERTY_TYPE: rent
    events:
      - schedule: cron(46 0 1 * ? *)

  # Median monthly SELLING price for LAND in Riga
  regional-data-land-sell-monthly:
    handler: src/regional-data.run
    environment:
      REGION: riga
      PROPERTY_CATEGORY: land
      PROPERTY_TYPE: sell
    events:
      - schedule: cron(50 0 1 * ? *)
  regional-price-per-sqm-land-sell-monthly:
    name: RegionalPricePerSqmLandSellMonthly
    handler: src/regional-price-per-sqm.run
    environment:
      REGION: riga
      PROPERTY_CATEGORY: land
      PROPERTY_TYPE: sell
    events:
      - schedule: cron(51 0 1 * ? *)

  # Median monthly RENT price for LAND in Riga
  regional-data-land-rent-monthly:
    handler: src/regional-data.run
    environment:
      REGION: riga
      PROPERTY_CATEGORY: land
      PROPERTY_TYPE: rent
    events:
      - schedule: cron(55 0 1 * ? *)
  regional-price-per-sqm-land-rent-monthly:
    name: RegionalPricePerSqmLandRentMonthly
    handler: src/regional-price-per-sqm.run
    environment:
      REGION: riga
      PROPERTY_CATEGORY: land
      PROPERTY_TYPE: rent
    events:
      - schedule: cron(56 0 1 * ? *)

  # Median monthly SELLING price for APARTMENTS in Latvia
  regional-data-apartment-sell-monthly-lv:
    handler: src/regional-data.run
    timeout: 200
    environment:
      REGION: latvia
      PROPERTY_CATEGORY: apartment
      PROPERTY_TYPE: sell
    events:
      - schedule: cron(32 0 1 * ? *)
  regional-price-per-sqm-apartment-sell-monthly-lv:
    name: RegionalPricePerSqmApartmentSellMonthlyLv
    handler: src/regional-price-per-sqm.run
    environment:
      REGION: latvia
      PROPERTY_CATEGORY: apartment
      PROPERTY_TYPE: sell
    events:
      - schedule: cron(33 0 1 * ? *)

  # Median monthly RENT price for APARTMENTS in Latvia
  regional-data-apartment-rent-monthly-lv:
    handler: src/regional-data.run
    timeout: 200
    environment:
      REGION: latvia
      PROPERTY_CATEGORY: apartment
      PROPERTY_TYPE: rent
    events:
      - schedule: cron(37 0 1 * ? *)
  regional-price-per-sqm-apartment-rent-monthly-lv:
    name: RegionalPricePerSqmApartmentRentMonthlyLv
    handler: src/regional-price-per-sqm.run
    environment:
      REGION: latvia
      PROPERTY_CATEGORY: apartment
      PROPERTY_TYPE: rent
    events:
      - schedule: cron(38 0 1 * ? *)

  # Median monthly SELLING price for HOUSES in Latvia
  regional-data-house-sell-monthly-lv:
    handler: src/regional-data.run
    timeout: 200
    environment:
      REGION: latvia
      PROPERTY_CATEGORY: house
      PROPERTY_TYPE: sell
    events:
      - schedule: cron(42 0 1 * ? *)
  regional-price-per-sqm-house-sell-monthly-lv:
    name: RegionalPricePerSqmHouseSellMonthlyLv
    handler: src/regional-price-per-sqm.run
    environment:
      REGION: latvia
      PROPERTY_CATEGORY: house
      PROPERTY_TYPE: sell
    events:
      - schedule: cron(43 0 1 * ? *)

  # Median monthly RENT price for HOUSES in Latvia
  regional-data-house-rent-monthly-lv:
    handler: src/regional-data.run
    timeout: 200
    environment:
      REGION: latvia
      PROPERTY_CATEGORY: house
      PROPERTY_TYPE: rent
    events:
      - schedule: cron(47 0 1 * ? *)
  regional-price-per-sqm-house-rent-monthly-lv:
    name: RegionalPricePerSqmHouseRentMonthlyLv
    handler: src/regional-price-per-sqm.run
    environment:
      REGION: latvia
      PROPERTY_CATEGORY: house
      PROPERTY_TYPE: rent
    events:
      - schedule: cron(48 0 1 * ? *)

  # Median monthly SELLING price for LAND in Latvia
  regional-data-land-sell-monthly-lv:
    handler: src/regional-data.run
    timeout: 200
    environment:
      REGION: latvia
      PROPERTY_CATEGORY: land
      PROPERTY_TYPE: sell

  # Median monthly RENT price for LAND in Latvia
  regional-data-land-rent-monthly-lv:
    handler: src/regional-data.run
    timeout: 200
    environment:
      REGION: latvia
      PROPERTY_CATEGORY: land
      PROPERTY_TYPE: rent

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
