service: sls-data-extraction

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs6.10
  cfLogs: true
  versionFunctions: false
  environment: ${file(serverless.env.yml)}

functions:
  # Daily statistics for all properties: sell
  base-data-sell:
    handler: src/base-data.run
    environment:
      PROPERTY_CATEGORY: sell
    events:
      - schedule: cron(0 0 * * *) # every day at 00:00

  # Daily statistics for all properties: buy
  base-data-buy:
    handler: src/base-data.run
    environment:
      PROPERTY_CATEGORY: buy
    events:
      - schedule: cron(0 0 * * *) # every day at 00:00

  # Daily statistics for all properties: rent
  base-data-rent:
    handler: src/base-data.run
    environment:
      PROPERTY_CATEGORY: rent
    events:
      - schedule: cron(0 0 * * *) # every day at 00:00

  # Daily statistics for all properties: want-to-rent
  base-data-want-to-rent:
    handler: src/base-data.run
    environment:
      PROPERTY_CATEGORY: want_to_rent
    events:
      - schedule: cron(0 0 * * *) # every day at 00:00

  # Weekly market share analysis
  market-share:
    handler: src/market-share.run
    events:
      - schedule: rate(1 week)

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
