service: sls-data-extraction

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs6.10
  cfLogs: true
  versionFunctions: false
  environment:
    DB_HOST: ${file(serverless.env.yml):DB_HOST, env:DB_HOST}
    DB_DATABASE: ${file(serverless.env.yml):DB_DATABASE, env:DB_DATABASE}
    DB_USERNAME: ${file(serverless.env.yml):DB_USERNAME, env:DB_USERNAME}
    DB_PASSWORD: ${file(serverless.env.yml):DB_PASSWORD, env:DB_PASSWORD}
    GITHUB_TOKEN: ${file(serverless.env.yml):GITHUB_TOKEN, env:GITHUB_TOKEN}

functions:
  # Daily statistics for all properties: sell
  base-data-sell:
    handler: src/base-data.run
    environment:
      PROPERTY_CATEGORY: sell
    events:
      - schedule: cron(15 0 * * ? *)

  # Daily statistics for all properties: buy
  base-data-buy:
    handler: src/base-data.run
    environment:
      PROPERTY_CATEGORY: buy
    events:
      - schedule: cron(10 0 * * ? *)

  # Daily statistics for all properties: rent
  base-data-rent:
    handler: src/base-data.run
    environment:
      PROPERTY_CATEGORY: rent
    events:
      - schedule: cron(5 0 * * ? *)

  # Daily statistics for all properties: want-to-rent
  base-data-want-to-rent:
    handler: src/base-data.run
    environment:
      PROPERTY_CATEGORY: want_to_rent
    events:
      - schedule: cron(0 0 * * ? *)

  # Weekly market share analysis
  market-share:
    handler: src/market-share.run
    events:
      - schedule: rate(7 days)

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
